export const videos = [
  {
    id: 1,
    name: "recorddeanestesiahistorial",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721926124/videos/recorddeanestesiahistorial.mp4",
  },
  {
    id: 2,
    name: "traslado_cirugia",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721926099/videos/traslado_cirugia.mp4",
  },
  {
    id: 3,
    name: "central_de_impresion_envio_de_correos",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721926080/videos/central_de_impresion_envio_de_correos.mp4",
  },
  {
    id: 4,
    name: "toma_de_signos_vitales_nuevo",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721926047/videos/toma_de_signos_vitales_nuevo.mp4",
  },
  {
    id: 5,
    name: "antibiotico",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721926027/videos/antibiotico.mp4",
  },
  {
    id: 6,
    name: "interconsulta_terapia",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721926001/videos/interconsulta_terapia.mp4",
  },
  {
    id: 7,
    name: "ENVIO_ORDENES",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925971/videos/ENVIO_ORDENES.mp4",
  },
  {
    id: 8,
    name: "DEVOLUCIONMEDICAMETOS",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925948/videos/DEVOLUCIONMEDICAMETOS.mp4",
  },
  {
    id: 9,
    name: "confirmacion_de_medicamentos",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925929/videos/confirmacion_de_medicamentos.mp4",
  },
  {
    id: 10,
    name: "OXIGENO_TERAPIA",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925900/videos/OXIGENO_TERAPIA.mp4",
  },
  {
    id: 11,
    name: "bodegas_en_cero1",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925884/videos/bodegas_en_cero1.mp4",
  },
  {
    id: 12,
    name: "autorizar_procedimientos",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925864/videos/autorizar_procedimientos.mp4",
  },
  {
    id: 13,
    name: "colocacion_cateter1",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925846/videos/colocacion_cateter1.mp4",
  },
  {
    id: 14,
    name: "FIRMA",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925820/videos/FIRMA.mp4",
  },
  {
    id: 15,
    name: "NANDA2",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925793/videos/NANDA2.mp4",
  },
  {
    id: 16,
    name: "toxicos",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925773/videos/toxicos.mp4",
  },
  {
    id: 17,
    name: "seguimiento_cateter1",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721925738/videos/seguimiento_cateter1.mp4",
  },
  {
    id: 18,
    name: "NANDA1",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721924308/videos/NANDA1.wmv",
  },
  {
    id: 19,
    name: "patologia",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721923788/videos/patologia.mp4",
  },
  {
    id: 20,
    name: "cobros",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721923754/videos/cobros.mp4",
  },
  {
    id: 21,
    name: "tecnovigilancia",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721923705/videos/tecnovigilancia.mp4",
  },
  {
    id: 22,
    name: "mipres",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721923632/videos/mipres.wmv",
  },
  {
    id: 23,
    name: "traslado_paciente1",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721923582/videos/traslado_paciente1.mp4",
  },
  {
    id: 24,
    name: "solicitud_y_confirmacion",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721923495/videos/solicitud_y_confirmacion.mp4",
  },
  {
    id: 25,
    name: "no_contratado",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721923387/videos/no_contratado.mp4",
  },
  {
    id: 26,
    name: "suspender_dieta",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721923281/videos/suspender_dieta.mp4",
  },
  {
    id: 27,
    name: "venopuncion",
    titel: "",
    url: "https://res.cloudinary.com/dxmqlmslg/video/upload/v1721922598/videos/venopuncion.mp4",
  },
];
